# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta" do
  desc "ZQTA project."
  homepage "https://github.com/VinCSS-Public-Projects/ZQTA"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_v1.0.0_darwin_amd64.tar.gz"
      sha256 "5d7389b2acee8646d568a8ad8a45856ace17d97fb50b9fc2e29c5b85b707df40"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_v1.0.0_darwin_arm64.tar.gz"
      sha256 "358cc9f5ccd06dd87d81724a7bd67e9c93c683b7159d474d666a1a5bd63c87a8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_v1.0.0_linux_amd64.tar.gz"
      sha256 "00d96b32366825c4533d9365bdb1011ae85cfea7546ef06de673619b8f150b76"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_v1.0.0_linux_arm64.tar.gz"
      sha256 "ec6b1c8a5fbd2a3a9a6d13ce8a3fee937b3477b030876cd64cecdbb8d035b4c4"
    end
  end

  # No zap stanza required
end
