# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta" do
  desc "ZQTA project."
  homepage "https://github.com/VinCSS-Public-Projects/ZQTA"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_1.0.0_darwin_amd64.tar.gz"
      sha256 "521e2bdb3e2f195cd02db0c75386993d10a6df9b4c4756af0d9034e5f1f69baa"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta_1.0.0_darwin_arm64.tar.gz"
      sha256 "6bd11ae69f5873d502b70be0c258b76edccf871db121ebdec55611484e8cd9fb"
    end
  end

  # No zap stanza required
end
