# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zqta < Formula
  desc "ZQTA project."
  homepage "https://github.com/VinCSS-Public-Projects/ZQTA"
  version "0.59.10"
  license "BSD3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v0.59.10/zqta_0.59.10_darwin_amd64.tar.gz"
    sha256 "8d359e32a8823edea41faad8804f77c6958288fcefde6cfbc4001d4918ebc6eb"

    def install
      bin.install "zqta"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v0.59.10/zqta_0.59.10_darwin_arm64.tar.gz"
    sha256 "9b1de1d14909d1c99b799ee52ed7f9ff4dcd19f8d1246653d9f8b47b4395b2cd"

    def install
      bin.install "zqta"
    end
  end
end
