# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta-ui" do
  desc ""
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta-ui"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta-ui_1.0.0_darwin_amd64.tar.gz"
      sha256 "d00733a95cc15ad5e075d65c94a8f2cc369f1cbd3e5329b392b0c50c51cf7074"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v1.0.0/zqta-ui_1.0.0_darwin_arm64.tar.gz"
      sha256 "da2ade69b10e8aa896468d2d27acdbef2aa9a82ee19bc66eae2476a55cfba64f"
    end
  end

  # No zap stanza required
end
