# This file was generated by GoReleaser. DO NOT EDIT.
cask "zqta-ui" do
  desc ""
  homepage ""
  version "0.59.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zqta-ui"

  on_macos do
    on_intel do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v0.59.12/zqta-ui_0.59.12_darwin_amd64.tar.gz"
      sha256 "9d77ab0e37ce66a0db3f3af86f108b937cd32a24446bc5ddaf5f6da6f2bd9ffa"
    end
    on_arm do
      url "https://github.com/VinCSS-Public-Projects/ZQTA/releases/download/v0.59.12/zqta-ui_0.59.12_darwin_arm64.tar.gz"
      sha256 "a0fe926a447e8eeb4be96d47122d796f081c24568b790ddaca95f5ec3042bda9"
    end
  end

  # No zap stanza required
end
